services:

  ### database
  postgres:
    image: postgres:16
    restart: unless-stopped
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    # volumes:
    #   - ${DB_PATH}:/var/lib/postgresql/data
    ports:
      - "5432:5432"
