@host=http://localhost:8888

### sign up
post {{host}}/v1/auth/signup
Content-Type: application/json

{
    "login": "admin",
    "password": "12345678901234567890"
}

### sign in
post {{host}}/v1/auth/signin
Content-Type: application/json

{
    "login": "admin",
    "password": "12345678901234567890"
}
